[build]
builder = "NIXPACKS"

[build.nixpacks]
buildCmd = "yarn install && yarn build"
startCmd = "yarn workspace server start"

[build.nixpacksConfig]
nixpkgs = "nodejs_22"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60

[variables]
NODE_VERSION = "22.12.0"
NIXPACKS_NODE_VERSION = "22"